image: docker:stable
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - sh build.sh
    - |
        for SUFFIX in py web; do
          docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$SUFFIX;
        done
